### PR TITLE
Update Openresty 1.9.3.1

### PR DESCRIPTION
**Pull request by josephpage**
Changelog : https://openresty.org/#ChangeLog1009003

Thanks !

### CODE REVIEW

**Comment by josephpage** [comment]
up ! @skozin

**Comment by josephpage** [comment]
help @skozin ! Thank you :smiley:

**Comment by thekantian** [comment]
Any news on an update here to 1.9?

**Comment by josephpage** [comment]
@skozin we need you !
Will update my PR to 1.9.3.2 soon. https://openresty.org/#ChangeLog1009003

**Comment by skozin** [comment]
@josephpage @thekantian Sorry guys, I completely missed all GitHub-related stuff.
@josephpage Merging this right now, thanks for your patience.

**Comment by thekantian** [comment]
Awesome,  no need for sorry… Thanks!

**Pull request merged**
